// BG.About - the About screen: SPAN as an open-source demo of agentic development by umage.ai, and the
// "umage.ai presents" credit above the logo on the title screen.
// about: feature module (loaded after main.js, history.js and pwa.js, before mobile.js).
// Hooks: wraps BG.Hud.init to add the title credit, the title's About button, the About row in Settings and the
// About modal; never edits other modules' state. The numbers come from BG.AboutData (js/features/about-data.js,
// generated by tools/gen-about.js). Every use of the umage.ai logo links to https://umage.ai in a new tab
// (target=_blank: an installed app hands the link to the browser). The logos are the official files in
// assets/brand/, used unmodified; the white one, since every surface it sits on here is dark.
(function (root) {
  'use strict';
  const BG = (root.BG = root.BG || {});
  const doc = root.document;

  const UMAGE = 'https://umage.ai';
  const REPO = 'https://github.com/umage-ai/SpanGame';
  const LOGO = 'assets/brand/umage-ai-logo-white.svg';   // 160.48 x 57.08: "umage." over "ai"
  const MARK = 'assets/brand/umage-ai-mark.svg';
  const EXT = 'target="_blank" rel="noopener"';

  function I() { return BG.i18n || null; }
  function t(k, p) { return I() ? I().t(k, p) : k; }
  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  }
  function num(n) { return I() ? I().num(n) : String(n); }
  // 'YYYY-MM-DD' -> "4 Oct 2026" / "4. okt. 2026"
  function day(s) { return s && I() ? I().date(+String(s).replace(/-/g, '')) : (s || ''); }
  function sfx(name) { try { if (BG.Audio) BG.Audio.play(name); } catch (e) { /* */ } }
  function safe(fn) { try { return fn(); } catch (e) { if (root.console) console.error(e); return undefined; } }
  function data() { return BG.AboutData || null; }
  // calendar days from the first commit to the release (both days count)
  function daysBetween(a, b) {
    const d = s => Date.UTC(+s.slice(0, 4), +s.slice(5, 7) - 1, +s.slice(8, 10));
    return Math.round((d(b) - d(a)) / 86400000) + 1;
  }

  // small line icons (24 x 24, stroked like BG.Hud.icon)
  const P = {
    spec: '<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/><path d="M9 12h6M9 16h6"/>',
    agents: '<path d="M3 6h12M3 12h12M3 18h12"/><path d="M15 3.5l3.5 2.5L15 8.5M15 9.5l3.5 2.5-3.5 2.5M15 15.5l3.5 2.5-3.5 2.5"/>',
    prove: '<path d="M12 3l7 3v5c0 4.5-3 8-7 10-4-2-7-5.5-7-10V6z"/><path d="M8.5 12l2.5 2.5 4.5-5"/>',
    review: '<circle cx="10.5" cy="10.5" r="6.5"/><path d="M15.3 15.3L21 21"/><path d="M7.8 10.6l2 2 3.6-3.6"/>',
    release: '<path d="M5 21V4"/><path d="M5 4h11l-2 4 2 4H5"/>',
    ext: '<path d="M14 4h6v6"/><path d="M20 4l-9 9"/><path d="M18 14v5a1 1 0 01-1 1H5a1 1 0 01-1-1V7a1 1 0 011-1h5"/>',
    code: '<path d="M8 7l-5 5 5 5M16 7l5 5-5 5M13.5 4l-3 16"/>',
    book: '<path d="M4 19.5V5a2 2 0 012-2h14v15H6a2 2 0 00-2 2z"/><path d="M20 18v3H6"/>',
    bug: '<path d="M8 9a4 4 0 018 0v5a4 4 0 01-8 0z"/><path d="M12 11v7M3 13h5M16 13h5M4 7l4 2.5M20 7l-4 2.5M4 19l4-2.5M20 19l-4-2.5"/>',
    scale: '<path d="M12 4v16M7 20h10M5 7h14"/><path d="M5 7l-3 6a3 3 0 006 0zM19 7l-3 6a3 3 0 006 0z"/>',
    tag: '<path d="M3 12V4h8l10 10-8 8z"/><circle cx="7.5" cy="8.5" r="1.4"/>',
    image: '<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="2"/><path d="M21 16l-5-5-9 9"/>',
    pen: '<path d="M16.5 3.5l4 4L8 20H4v-4z"/><path d="M14 6l4 4"/>',
    wave: '<path d="M3 12h2M7 8v8M11 5v14M15 8v8M19 11v2"/>',
    info: '<circle cx="12" cy="12" r="9"/><path d="M12 11v6"/><path d="M12 7.6v.2"/>',
    close: '<path d="M6 6l12 12M18 6L6 18"/>',
    chev: '<path d="M9 6l6 6-6 6"/>',
    arrow: '<path d="M5 12h14"/><path d="M13 6l6 6-6 6"/>',
    spark: '<path d="M12 3v4M12 17v4M3 12h4M17 12h4M6 6l2.5 2.5M15.5 15.5L18 18M18 6l-2.5 2.5M8.5 15.5L6 18"/>',
  };
  function icon(name, cls) {
    return '<svg class="ico ' + (cls || '') + '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + (P[name] || '') + '</svg>';
  }
  function logoImg(cls, h) {
    return '<img class="' + cls + '" src="' + LOGO + '" alt="umage.ai" width="' + Math.round(h * 2.811) + '" height="' + h + '" draggable="false">';
  }

  const STEPS = ['spec', 'agents', 'prove', 'review', 'release'];
  const CREDITS = [['made', 'spark'], ['bg', 'image'], ['sprites', 'pen'], ['audio', 'wave'], ['license', 'scale']];
  function links(d) {
    return [
      { id: 'umage', href: UMAGE, ico: 'ext' },
      { id: 'source', href: REPO, ico: 'code' },
      { id: 'docs', href: REPO + '/tree/main/docs', ico: 'book' },
      { id: 'license', href: REPO + '/blob/main/LICENSE', ico: 'scale' },
      { id: 'issues', href: REPO + '/issues', ico: 'bug' },
      { id: 'notes', href: (d && d.releaseNotes) || REPO + '/releases', ico: 'tag' },
    ];
  }

  const About = BG.About = {
    UMAGE, REPO, links, daysBetween,
    open: () => open(),
    close: () => close(),
    isOpen: () => !!(el.modal && el.modal.classList.contains('show')),
  };
  const el = {};

  if (!doc || !BG.Hud) return;
  const Hud = BG.Hud;

  // ------------------------------------------------------------ DOM
  function h(html) { const tp = doc.createElement('template'); tp.innerHTML = html.trim(); return tp.content.firstElementChild; }

  const origInit = Hud.init;
  Hud.init = function () {
    const out = origInit.apply(this, arguments);
    safe(() => build(this));
    return out;
  };

  function build(hud) {
    const ui = hud.root || doc.getElementById('ui');
    if (!ui) return;
    const d = data();

    // title: "umage.ai presents" above the logo, About under the entry buttons (a corner pill on most layouts)
    const wrap = hud.el.title && hud.el.title.querySelector('.title-wrap');
    if (wrap) {
      const pres = h('<a class="abt-presents" href="' + UMAGE + '" ' + EXT + ' data-i18n-title="features.about.visit">' +
        logoImg('abt-presents-logo', 26) + '<span data-i18n="features.about.presents"></span></a>');
      wrap.insertBefore(pres, wrap.firstChild);
      const btn = h('<button class="btn btn-glass abt-title-btn" type="button" data-about="open" data-i18n-title="features.about.title">' +
        icon('info') + '<span data-i18n="features.about.button"></span></button>');
      const tb = wrap.querySelector('.title-buttons');
      wrap.insertBefore(btn, tb ? tb.nextSibling : null);
      btn.addEventListener('click', e => { e.stopPropagation(); sfx('click'); open(); });
      pres.addEventListener('click', e => e.stopPropagation());
      if (I()) { I().apply(pres); I().apply(btn); }
      el.presents = pres; el.titleBtn = btn;
    }

    // the modal
    const modal = h(`<div id="about" class="modal abt-modal" role="dialog" aria-modal="true" data-i18n-aria="features.about.title">
        <div class="modal-card glass abt-card" tabindex="-1">
          <div class="modal-head"><h3 data-i18n="features.about.title">${icon('info')}</h3><button class="btn btn-icon btn-ghost" type="button" data-aact="close" data-i18n-title="features.closeEsc">${icon('close')}</button></div>
          <div class="abt-body">
            <header class="abt-hero">
              <div class="abt-span">
                <div class="abt-wordmark" aria-label="SPAN"><span>S</span><span>P</span><span>A</span><span>N</span></div>
                <div class="abt-sub"><span class="abt-ver" data-aref="ver"></span><span data-i18n="features.about.subtitle"></span></div>
              </div>
              <a class="abt-umage" href="${UMAGE}" ${EXT} data-i18n-title="features.about.visit" data-i18n-aria="features.about.visit">
                <small data-i18n="features.about.by"></small>${logoImg('abt-umage-logo', 34)}</a>
            </header>
            <section class="abt-intro">
              <p class="abt-eyebrow" data-i18n="features.about.eyebrow"></p>
              <p data-i18n-html="features.about.p1"></p>
              <p data-i18n-html="features.about.p2"></p>
              <p data-i18n-html="features.about.p3"></p>
            </section>
            <section class="abt-sec" data-aref="numbers">
              <h4 data-i18n="features.about.numbers"></h4>
              <div class="abt-stats" data-aref="stats"></div>
              <p class="abt-note" data-aref="asof"></p>
            </section>
            <section class="abt-sec">
              <h4 data-i18n="features.about.how"></h4>
              <ol class="abt-steps">${STEPS.map((s, i) => `<li class="abt-step"><span class="abt-step-ico">${icon(s)}<i>${i + 1}</i></span>
                <b data-i18n="features.about.step.${s}"></b><small data-i18n="features.about.step.${s}.desc"></small></li>`).join('')}</ol>
            </section>
            <section class="abt-sec">
              <h4 data-i18n="features.about.credits"></h4>
              <ul class="abt-credits">${CREDITS.map(([k, ic]) => `<li>${icon(ic)}<span data-i18n-html="features.about.credit.${k}"></span></li>`).join('')}</ul>
            </section>
            <section class="abt-sec">
              <h4 data-i18n="features.about.more"></h4>
              <div class="abt-links" data-aref="links"></div>
            </section>
            <a class="abt-cta" href="${UMAGE}" ${EXT}>
              <img class="abt-cta-mark" src="${MARK}" alt="umage.ai" width="44" height="44" draggable="false">
              <span class="abt-cta-text"><b data-i18n="features.about.cta"></b><small data-i18n="features.about.ctaSub"></small></span>
              <span class="abt-cta-go"><span data-i18n="features.about.ctaLink"></span>${icon('arrow')}</span>
            </a>
          </div>
          <div class="modal-foot"><span class="abt-foot" data-aref="foot"></span><button class="btn btn-primary" type="button" data-aact="close" data-i18n="core.done"></button></div>
        </div>
      </div>`);
    if (I()) I().apply(modal);
    ui.appendChild(modal);
    el.modal = modal;
    hud.el.about = modal;
    modal.addEventListener('click', e => {
      if (e.target === modal) { close(); return; }
      const a = e.target.closest('[data-aact]');
      if (a && a.dataset.aact === 'close') { sfx('click'); close(); return; }
      if (e.target.closest('a[href]')) sfx('click');
    });
    if (!d) { const n = modal.querySelector('[data-aref=numbers]'); if (n) n.hidden = true; }

    // settings: an About row at the bottom (above Done)
    const card = hud.el.settings && hud.el.settings.querySelector('.modal-card');
    if (card) {
      const row = h('<button type="button" class="set-row abt-set-row" data-about="settings"><span data-i18n="features.about.title">' + icon('info') + '</span>' +
        '<small class="abt-set-ver" data-aref="setVer"></small>' + icon('chev', 'abt-chev') + '</button>');
      if (I()) I().apply(row);
      card.insertBefore(row, card.querySelector('.modal-foot'));
      row.addEventListener('click', e => {
        e.stopPropagation(); sfx('click');
        if (Hud.closeSettings) Hud.closeSettings();
        open();
      });
      el.setRow = row;
    }
    render();
  }

  // ------------------------------------------------------------ text built in code (numbers, dates, links)
  function render() {
    const m = el.modal;
    if (!m) return;
    const d = data();
    const ver = d ? d.version : '';
    m.querySelector('[data-aref=ver]').textContent = ver;
    if (el.setRow) el.setRow.querySelector('[data-aref=setVer]').textContent = ver;
    m.querySelector('[data-aref=links]').innerHTML = links(d).map(l =>
      '<a class="btn btn-glass abt-link" data-alink="' + l.id + '" href="' + esc(l.href) + '" ' + EXT + '>' + icon(l.ico) +
      '<span>' + esc(l.id === 'umage' ? 'umage.ai' : t('features.about.link.' + l.id, { version: ver })) + '</span></a>').join('');
    m.querySelector('[data-aref=foot]').textContent = d ? t('features.about.foot', { version: ver }) : '';
    if (!d) return;
    const tile = (value, label, cls, sub) => '<div class="abt-stat ' + (cls || '') + '"><b>' + esc(value) + '</b><span>' + esc(label) + '</span>' +
      (sub ? '<small>' + esc(sub) + '</small>' : '') + '</div>';
    const lines = (d.jsLines && d.jsLines.total) || 0;
    let span = '';
    if (d.firstCommit) {
      const to = d.released || d.asOf;
      span = tile(t('features.about.stat.days', { n: daysBetween(d.firstCommit, to) }),
        t(d.released ? 'features.about.stat.toRelease' : 'features.about.stat.toDate', { version: ver }), 'abt-stat-wide',
        day(d.firstCommit) + ' → ' + day(to));
    }
    const ag = d.agentic;
    m.querySelector('[data-aref=stats]').innerHTML = [
      ag && ag.agents ? tile(num(ag.agents), t('features.about.stat.agents', { n: ag.agents }), 'abt-stat-wide',
        t('features.about.stat.agentsSplit', { workflows: num(ag.workflows), calls: num(Math.round(ag.toolCalls / 100) * 100) })) : '',
      tile(num(d.levels), t('features.about.stat.levels', { n: d.campaigns })),
      tile(num(d.designs), t('features.about.stat.designs')),
      tile(num(d.testSuites), t('features.about.stat.suites', { n: d.testSuites })),
      tile(num(d.languages), t('features.about.stat.languages', { n: d.languages })),
      tile(num(lines), t('features.about.stat.lines'), '', d.jsLines && d.jsLines.game ? t('features.about.stat.linesSplit', { game: num(d.jsLines.game), tools: num(d.jsLines.tools) }) : ''),
      tile(num(d.commits), t('features.about.stat.commits', { n: d.commits })),
      span,
    ].join('');
    m.querySelector('[data-aref=asof]').textContent = t('features.about.asOf', { date: day(d.asOf), version: ver });
  }

  // focus: the card takes it on open (so Tab starts inside and the arrow keys scroll it), Tab stays inside while it
  // is open, and focus returns to where it was on close
  let returnFocus = null;
  function open() {
    const m = el.modal;
    if (!m) return;
    render();
    const a = doc.activeElement;
    returnFocus = a && a !== doc.body && !m.contains(a) ? a : null;
    m.classList.add('show');
    const body = m.querySelector('.abt-body');
    if (body) body.scrollTop = 0;
    const card = m.querySelector('.abt-card');
    if (card) safe(() => card.focus({ preventScroll: true }));
  }
  function close() {
    if (!el.modal || !el.modal.classList.contains('show')) return;
    el.modal.classList.remove('show');
    const a = doc.activeElement;
    if (a && el.modal.contains(a) && a.blur) a.blur();
    if (returnFocus && returnFocus.isConnected) safe(() => returnFocus.focus({ preventScroll: true }));
    returnFocus = null;
  }
  function trapTab(e) {
    const f = Array.from(el.modal.querySelectorAll('a[href], button:not(:disabled)')).filter(x => x.offsetParent !== null);
    if (!f.length) return;
    const a = doc.activeElement, i = f.indexOf(a);
    if (!el.modal.contains(a) || (e.shiftKey && i <= 0) || (!e.shiftKey && i === f.length - 1)) {
      e.preventDefault();
      (e.shiftKey ? f[f.length - 1] : f[0]).focus();
    }
  }

  if (I()) I().on('languagechange', () => safe(render));
  // Esc closes the About screen; other keys must not reach the game while it is open
  root.addEventListener('keydown', e => {
    if (!About.isOpen()) return;
    if (e.key === 'Escape') { e.preventDefault(); close(); }
    else if (e.key === 'Tab') trapTab(e);
    e.stopImmediatePropagation();
  }, true);
})(typeof window !== 'undefined' ? window : globalThis);
