// SPAN about: the numbers on the About screen (BG.AboutData, shown by js/features/about.js).
// GENERATED by tools/gen-about.js - do not edit by hand; refresh with: node tools/gen-about.js
(function (root) {
  'use strict';
  const BG = (root.BG = root.BG || {});
  BG.AboutData = {
    "version": "v1.1.0",
    "versionFrom": "tag",
    "released": "2026-10-04",
    "firstCommit": "2026-10-02",
    "asOf": "2026-10-05",
    "commits": 45,
    "levels": 90,
    "campaigns": 3,
    "campaignLevels": {
      "road": 58,
      "rail": 20,
      "famous": 12
    },
    "designs": 428,
    "levelDesigns": 180,
    "badgeDesigns": 248,
    "testSuites": 32,
    "nodeSuites": 18,
    "browserSuites": 14,
    "languages": 2,
    "jsLines": {
      "total": 34846,
      "game": 25719,
      "tools": 9127
    },
    "jsFiles": 89,
    "repo": "https://github.com/umage-ai/SpanGame",
    "releaseNotes": "https://github.com/umage-ai/SpanGame/releases/tag/v1.1.0",
    "agentic": {
      "agents": 77,
      "workflows": 13,
      "toolCalls": 6150,
      "models": {
        "Claude Opus": 72,
        "Claude Sonnet": 5
      },
      "asOf": "2026-10-05"
    }
  };
})(typeof window !== 'undefined' ? window : globalThis);
