// pwa: SPAN service worker - offline play once the site has been opened over http(s).
// Registered by js/features/pwa.js (never on file://).
//  - install:  precaches every shipped game file (list + version generated by tools/gen-precache.js)
//  - activate: deletes older span-precache-* caches, takes control of open pages
//  - fetch:    index.html / navigations -> network-first (cached copy when offline or slow)
//              everything else (css, js, assets) -> cache-first, then network (and cached)
//  - update:   a new version waits until the page posts {type:'SKIP_WAITING'} (the "tap to reload" toast)
'use strict';

// <precache> generated by tools/gen-precache.js - do not edit by hand
const VERSION = '10c3152c8a6a';
const PRECACHE = [
  'index.html',
  'manifest.webmanifest',
  'css/history.css',
  'css/mobile.css',
  'css/pwa.css',
  'css/style.css',
  'js/core/levels.js',
  'js/core/materials.js',
  'js/core/model.js',
  'js/core/physics.js',
  'js/core/templates.js',
  'js/core/trains.js',
  'js/core/vehicles.js',
  'js/features/history.js',
  'js/features/mobile.js',
  'js/features/pwa.js',
  'js/main.js',
  'js/render/effects.js',
  'js/render/renderer.js',
  'js/ui/audio.js',
  'js/ui/editor.js',
  'js/ui/hud.js',
  'js/ui/storage.js',
  'assets/bg/autumn.jpg',
  'assets/bg/canyon.jpg',
  'assets/bg/city.jpg',
  'assets/bg/desert.jpg',
  'assets/bg/meadow.jpg',
  'assets/bg/night.jpg',
  'assets/bg/snow.jpg',
  'assets/bg/tropical.jpg',
  'assets/bg/volcanic.jpg',
  'assets/icons/app/apple-touch-icon.png',
  'assets/icons/app/icon-192.png',
  'assets/icons/app/icon-512.png',
  'assets/icons/app/icon-maskable-192.png',
  'assets/icons/app/icon-maskable-512.png',
  'assets/icons/app/icon-maskable.svg',
  'assets/icons/app/icon.svg',
  'assets/icons/build.svg',
  'assets/icons/cable.svg',
  'assets/icons/edit.svg',
  'assets/icons/erase.svg',
  'assets/icons/fast.svg',
  'assets/icons/home.svg',
  'assets/icons/lock.svg',
  'assets/icons/mirror.svg',
  'assets/icons/mute.svg',
  'assets/icons/next.svg',
  'assets/icons/pause.svg',
  'assets/icons/pier.svg',
  'assets/icons/play.svg',
  'assets/icons/redo.svg',
  'assets/icons/reinforced_road.svg',
  'assets/icons/restart.svg',
  'assets/icons/road.svg',
  'assets/icons/rope.svg',
  'assets/icons/select.svg',
  'assets/icons/settings.svg',
  'assets/icons/slow.svg',
  'assets/icons/sound.svg',
  'assets/icons/star.svg',
  'assets/icons/star_empty.svg',
  'assets/icons/steel.svg',
  'assets/icons/templates.svg',
  'assets/icons/trash.svg',
  'assets/icons/undo.svg',
  'assets/icons/wood.svg',
  'assets/sprites/anchor.svg',
  'assets/sprites/bus.svg',
  'assets/sprites/car.svg',
  'assets/sprites/heavy.svg',
  'assets/sprites/joint.svg',
  'assets/sprites/rail/bogie.svg',
  'assets/sprites/rail/bogie3.svg',
  'assets/sprites/rail/boxcar.svg',
  'assets/sprites/rail/coach.svg',
  'assets/sprites/rail/handcar.svg',
  'assets/sprites/rail/handcar_lever.svg',
  'assets/sprites/rail/hs_coach.svg',
  'assets/sprites/rail/hs_power.svg',
  'assets/sprites/rail/loco_diesel.svg',
  'assets/sprites/rail/loco_steam.svg',
  'assets/sprites/rail/ore_wagon.svg',
  'assets/sprites/rail/rail_driver.svg',
  'assets/sprites/rail/rail_wheel.svg',
  'assets/sprites/rail/rail_wheel_spoked.svg',
  'assets/sprites/rail/tank_wagon.svg',
  'assets/sprites/rail/tender.svg',
  'assets/sprites/rail/tram.svg',
  'assets/sprites/semi.svg',
  'assets/sprites/tanker.svg',
  'assets/sprites/truck.svg',
  'assets/sprites/van.svg',
  'assets/sprites/wheel.svg',
  'assets/sprites/wheel_heavy.svg',
];
// </precache>

const PREFIX = 'span-precache-';
const CACHE = PREFIX + VERSION;
const NET_TIMEOUT_MS = 3500;
const scoped = p => new URL(p, self.registration.scope).href;
const INDEX = () => scoped('index.html');

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // cache:'reload' skips the HTTP cache so a deploy never precaches a stale file
    await cache.addAll(PRECACHE.map(p => new Request(scoped(p), { cache: 'reload' })));
    // first install: nothing to replace, so activate straight away. Updates wait for the player.
    if (!self.registration.active) await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', event => {
  const d = event.data || {};
  if (d.type === 'SKIP_WAITING') self.skipWaiting();
  else if (d.type === 'GET_VERSION' && event.ports && event.ports[0]) {
    event.ports[0].postMessage({ version: VERSION, cache: CACHE, files: PRECACHE.length });
  }
});

function isPage(req, url) {
  if (req.mode === 'navigate') return true;
  const scope = new URL(self.registration.scope);
  return url.pathname === scope.pathname || url.pathname === scope.pathname + 'index.html';
}

async function networkFirst(req) {
  const cache = await caches.open(CACHE);
  const net = fetch(req).then(res => {
    if (res && res.ok && res.type === 'basic') cache.put(INDEX(), res.clone());
    return res;
  });
  try {
    // a slow mobile connection should not hold the game hostage: fall back to the cache after a while
    const res = await Promise.race([net, new Promise((_, rej) => setTimeout(() => rej(new Error('timeout')), NET_TIMEOUT_MS))]);
    if (res && res.ok) return res;
    const cached = await cache.match(INDEX());
    return cached || res;
  } catch (e) {
    const cached = await cache.match(INDEX());
    if (cached) { net.catch(() => {}); return cached; }
    return net; // nothing cached: let the network outcome (or error) through
  }
}

async function cacheFirst(req) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(req, { ignoreSearch: true });
  if (hit) return hit;
  try {
    const res = await fetch(req);
    if (res && res.ok && res.type === 'basic') cache.put(req, res.clone());
    return res;
  } catch (e) {
    return new Response('', { status: 504, statusText: 'Offline' });
  }
}

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname.endsWith('/sw.js')) return;
  event.respondWith(isPage(req, url) ? networkFirst(req) : cacheFirst(req));
});
