#!/usr/bin/env node
// SPAN — assembles tools/levels/level-NN.json into js/core/levels.js (BG.Levels, sorted by id).
// Tolerates partially-written/unparsable files (skips with a warning). Writes atomically.
'use strict';
const fs = require('fs');
const path = require('path');
const DIR = path.join(__dirname, 'levels');
const OUT = path.resolve(__dirname, '..', 'js', 'core', 'levels.js');
const levels = [];
for (const f of fs.readdirSync(DIR).filter(f => /^level-\d+\.json$/.test(f)).sort()) {
  try { levels.push(JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8'))); }
  catch (e) { console.warn('[build-levels] skipping ' + f + ': ' + e.message); }
}
levels.sort((a, b) => a.id - b.id);
const body = levels.map(l => '    ' + JSON.stringify(l)).join(',\n');
const src = `/* SPAN — level definitions (BG.Levels). GENERATED by tools/build-levels.js from tools/levels/*.json — do not edit by hand. */
(function (root) {
  'use strict';
  const BG = (root.BG = root.BG || {});
  BG.Levels = [
${body}
  ];
  // i18n (docs/I18N.md): name / hint are getters that read levels.<id>.name / .hint in the current language, and
  // the text fields of a famous bridge's history card read famous.<id>.<field> (facts: famous.<id>.fact1, ...).
  // The JSON text above is the fallback (and the English source of truth).
  const I = BG.i18n;
  if (I && I.lazy && I.levelText) {
    BG.Levels.forEach(lv => {
      const src = { id: lv.id, name: lv.name, hint: lv.hint };
      I.lazy(lv, { name: () => I.levelText(src, 'name'), hint: () => I.levelText(src, 'hint') });
      const H = lv.history;
      if (!H) return;
      const tx = (f, raw) => () => { const k = 'famous.' + lv.id + '.' + f; return I.has(k, 'en') ? I.t(k) : raw; };
      const map = {};
      Object.keys(H).forEach(f => { if (typeof H[f] === 'string' && f !== 'art') map[f] = tx(f, H[f]); });
      if (Array.isArray(H.facts)) { const facts = H.facts.slice(); map.facts = () => facts.map((x, i) => tx('fact' + (i + 1), x)()); }
      I.lazy(H, map);
    });
  }
})(typeof window !== 'undefined' ? window : globalThis);
`;
const tmp = OUT + '.' + process.pid + '.tmp';
fs.writeFileSync(tmp, src);
fs.renameSync(tmp, OUT);
console.log('[build-levels] wrote ' + levels.length + ' levels: ' + levels.map(l => l.id).join(','));
