#!/usr/bin/env node
// SPAN — assembles tools/levels/level-NN.json into js/core/levels.js (BG.Levels, sorted by id).
// Tolerates partially-written/unparsable files (skips with a warning). Writes atomically.
'use strict';
const fs = require('fs');
const path = require('path');
const DIR = path.join(__dirname, 'levels');
const OUT = path.resolve(__dirname, '..', 'js', 'core', 'levels.js');
const levels = [];
for (const f of fs.readdirSync(DIR).filter(f => /^level-\d+\.json$/.test(f)).sort()) {
  try { levels.push(JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8'))); }
  catch (e) { console.warn('[build-levels] skipping ' + f + ': ' + e.message); }
}
levels.sort((a, b) => a.id - b.id);
const body = levels.map(l => '    ' + JSON.stringify(l)).join(',\n');
const src = `/* SPAN — level definitions (BG.Levels). GENERATED by tools/build-levels.js from tools/levels/*.json — do not edit by hand. */
(function (root) {
  'use strict';
  const BG = (root.BG = root.BG || {});
  BG.Levels = [
${body}
  ];
})(typeof window !== 'undefined' ? window : globalThis);
`;
const tmp = OUT + '.' + process.pid + '.tmp';
fs.writeFileSync(tmp, src);
fs.renameSync(tmp, OUT);
console.log('[build-levels] wrote ' + levels.length + ' levels: ' + levels.map(l => l.id).join(','));
