// about: checks js/features/about-data.js, the generated numbers on the About screen (tools/gen-about.js).
// Usage: node tools/test-about.js
//   - the file exists, is marked as generated, loads in Node and defines BG.AboutData
//   - every field is present with the right type and a sane value (version, dates, counts, links)
//   - it is data only: no e-mail addresses, no functions
//   - the counts that the game itself knows (levels, campaigns, languages) match the game; refresh with
//     node tools/gen-about.js when they do not
//   - index.html loads the data before js/features/about.js, and the logos it uses exist
// Exit code 0 = all checks passed.
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const ROOT = path.resolve(__dirname, '..');
const FILE = path.join(ROOT, 'js', 'features', 'about-data.js');

const results = [];
const ok = (name, cond, info) => { results.push(!!cond); console.log((cond ? 'PASS ' : 'FAIL ') + name + (!cond && info !== undefined ? '  ' + JSON.stringify(info) : '')); };

ok('js/features/about-data.js exists', fs.existsSync(FILE));
const src = fs.existsSync(FILE) ? fs.readFileSync(FILE, 'utf8') : '';
ok('marked as generated by tools/gen-about.js', /GENERATED by tools\/gen-about\.js/.test(src));
const sandbox = {};
let loaded = null;
try { vm.runInNewContext(src, { globalThis: sandbox, window: undefined }); loaded = sandbox.BG && sandbox.BG.AboutData; } catch (e) { ok('loads in Node', false, e.message); }
ok('defines BG.AboutData', !!loaded && typeof loaded === 'object');
const D = loaded || {};

const DAY = /^\d{4}-\d{2}-\d{2}$/;
const isInt = (v, min) => Number.isInteger(v) && v >= (min || 0);
ok('version is a release tag or the package version (vX.Y.Z)', /^v\d+\.\d+\.\d+/.test(D.version) && ['tag', 'package.json'].includes(D.versionFrom), { version: D.version, from: D.versionFrom });
ok('dates are YYYY-MM-DD and in order (first commit <= release <= as of)', DAY.test(D.firstCommit) && DAY.test(D.asOf) && (D.released == null || DAY.test(D.released)) &&
  D.firstCommit <= (D.released || D.asOf) && (D.released || D.asOf) <= D.asOf, { first: D.firstCommit, released: D.released, asOf: D.asOf });
ok('counts are positive integers', ['commits', 'levels', 'campaigns', 'designs', 'levelDesigns', 'badgeDesigns', 'testSuites', 'nodeSuites', 'browserSuites', 'languages', 'jsFiles'].every(k => isInt(D[k], 1)),
  ['commits', 'levels', 'campaigns', 'designs', 'testSuites', 'languages'].map(k => k + '=' + D[k]));
ok('designs = level designs + badge designs; suites = node + browser', D.designs === D.levelDesigns + D.badgeDesigns && D.testSuites === D.nodeSuites + D.browserSuites);
ok('campaign levels add up to the level count', D.campaignLevels && Object.keys(D.campaignLevels).length === D.campaigns &&
  Object.values(D.campaignLevels).reduce((a, b) => a + b, 0) === D.levels, D.campaignLevels);
ok('lines of JavaScript: game + tools = total', D.jsLines && isInt(D.jsLines.game, 1000) && isInt(D.jsLines.tools, 100) && D.jsLines.total === D.jsLines.game + D.jsLines.tools, D.jsLines);
ok('links point at the public repository', D.repo === 'https://github.com/umage-ai/SpanGame' &&
  (D.releaseNotes === D.repo + '/releases/tag/' + D.version || (D.versionFrom !== 'tag' && D.releaseNotes === D.repo + '/releases')), { repo: D.repo, notes: D.releaseNotes });
ok('data only: no e-mail addresses, no functions', !/[\w.+-]+@[\w-]+\.[\w.]+/.test(src) && !/function\s*\(|=>/.test(src.replace(/^\(function \(root\) \{|\}\)\(typeof window[^\n]*$/gm, '')) &&
  JSON.stringify(D).length > 100);

// the numbers the game knows itself
const { BG } = require('./harness');
const camps = new Set(BG.Levels.map(l => l.campaign || 'road'));
ok('level and campaign counts match the game (else: node tools/gen-about.js)', D.levels === BG.Levels.length && D.campaigns === camps.size, { data: [D.levels, D.campaigns], game: [BG.Levels.length, camps.size] });
ok('language count matches BG.i18n (else: node tools/gen-about.js)', D.languages === BG.i18n.languages().length, { data: D.languages, game: BG.i18n.languages().length });
const suites = require('./run-tests.js');
ok('test suite count matches tools/run-tests.js (else: node tools/gen-about.js)', D.testSuites === suites.NODE.length + suites.BROWSER.length, { data: D.testSuites, runner: suites.NODE.length + suites.BROWSER.length });

const index = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const iData = index.indexOf('js/features/about-data.js'), iUi = index.indexOf('js/features/about.js');
ok('index.html loads about-data.js, then about.js, before mobile.js', iData > 0 && iUi > iData && iUi < index.indexOf('js/features/mobile.js') && index.indexOf('css/about.css') > 0);
ok('the umage.ai logos are in assets/brand/', ['umage-ai-logo.svg', 'umage-ai-logo-white.svg', 'umage-ai-mark.svg'].every(f => fs.existsSync(path.join(ROOT, 'assets', 'brand', f))));

const failed = results.filter(r => !r).length;
console.log(failed ? '\n' + failed + ' of ' + results.length + ' checks FAILED' : '\n' + results.length + '/' + results.length + ' checks passed');
process.exit(failed ? 1 : 0);
